apiVersion: v1
kind: Service
metadata:
  name: taskflow
  labels:
    app: taskflow
spec:
  type: ClusterIP
  selector:
    app: taskflow
    color: blue
  ports:
    - port: 8080
      targetPort: 8080
      name: http
